### ISSUE TITLE
媓钻护肤品失效

### ISSUE THREAD

**Issue by qiujiafei** [sudojia/AutoTaskScript#107]
### 📜 脚本名称

src/wx_mini/sudojia_hzhfp.js

### 🤔 问题描述

媓钻护肤品失效

### 🔄 重现过程

媓钻护肤品失效

### 🌐 网络自检

是

### 🔗 附加信息

```shell
## 开始执行... 2024-11-07 13:53:35


                  _         _  _        
  ___  _   _   __| |  ___  (_)(_)  __ _ 
 / __|| | | | / _` | / _ \ | || | / _` |
 \__ \| |_| || (_| || (_) || || || (_| |
 |___/ \__,_| \__,_| \___/_/ ||_| \__,_|
                         |__/           

【脚本作者】sudojia
【脚本地址】https://github.com/sudojia/AutoTaskScript
【当前版本】v1.0.0
【最新版本】v1.0.0
【最近更新】2024-08-18
【更新内容】媓钻小程序每日签到

开始执行媓钻护肤品

已随机分配 User-Agent

Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.48(0x1800302c) NetType/WIFI Language/zh_CN

*****第[1]个媓钻护肤品账号*****

❗️媓钻护肤品, 错误!
TypeError: Cannot read properties of undefined (reading 'data')
    at IlIlll11 (/ql/data/scripts/sudojia_AutoTaskScript/src/wx_mini/sudojia_hzhfp.js:15:49371)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async l1illll1 (/ql/data/scripts/sudojia_AutoTaskScript/src/wx_mini/sudojia_hzhfp.js:15:38116)
    at async /ql/data/scripts/sudojia_AutoTaskScript/src/wx_mini/sudojia_hzhfp.js:15:32386

🔔媓钻护肤品, 结束! 🕛 11.711 秒


## 执行结束... 2024-11-07 13:53:47  耗时 12 秒　　　　　
```

**Comment by sudojia** [comment]
重新获取 token 试试

![image](https://github.com/user-attachments/assets/f424dbde-d41b-47e9-8a7d-801d41105a97)
