### ISSUE TITLE
霸王茶姬脚本运行bug

### ISSUE THREAD

**Issue by starsink-d** [sudojia/AutoTaskScript#30]
脚本名称：sudojia_bwtea.js
问题描述；在运行霸王茶姬签到时，查看日志发生异常，错误日志如下：
********第【1】个霸王茶姬账号********
旧版-签到成功
TypeError: Cannot read properties of undefined (reading '0')
    at wdnmdt (/ql/scripts/sudojia_scripts_script/sudojia_bwtea.js:12:183360)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async wdnmds (/ql/scripts/sudojia_scripts_script/sudojia_bwtea.js:12:179967)
    at async wdnmdo (/ql/scripts/sudojia_scripts_script/sudojia_bwtea.js:12:160682)
    at async /ql/scripts/sudojia_scripts_script/sudojia_bwtea.js:12:156204

运行环境
青龙面板：2.11.3
运行其他脚本一切正常
![image](https://github.com/sudojia/scripts/assets/112603695/e7571e4f-9437-45aa-a80e-32b683cf66b2)

**Comment by sudojia** [comment]
拉取新脚本重试
